import React, { useState, useRef } from 'react';
import { UploadCloud, FileJson, AlertCircle, Loader2 } from 'lucide-react';
import { api } from '../services/api';
import type { ReportMetadata } from '../services/api';

interface UploadPanelProps {
  onUploadSuccess: (metadata: ReportMetadata) => void;
}

export const UploadPanel: React.FC<UploadPanelProps> = ({ onUploadSuccess }) => {
  const [file, setFile] = useState<File | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setError(null);
    if (e.target.files && e.target.files.length > 0) {
      const selectedFile = e.target.files[0];
      if (!selectedFile.name.endsWith('.json')) {
        setError('Only .json files are supported.');
        setFile(null);
        return;
      }
      setFile(selectedFile);
    }
  };

  const handleUpload = async () => {
    if (!file) {
      setError('Please select a JSON report.');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const response = await api.uploadReport(file);
      onUploadSuccess(response);
    } catch (err: any) {
      if (err.response?.data?.error) {
        setError(err.response.data.error);
      } else if (err.message === 'Network Error') {
        setError('Unable to connect to the analysis server.');
      } else {
        setError('An unexpected error occurred during upload.');
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-slate-800 rounded-xl border border-slate-700 overflow-hidden shadow-lg shadow-black/20">
      <div className="p-6">
        <h2 className="text-xl font-semibold text-white mb-2">Upload Security Report</h2>
        <p className="text-slate-400 mb-6 text-sm">
          Upload a JSON report generated by the vulnerability assessment engine.
        </p>

        <div 
          className="border-2 border-dashed border-slate-600 rounded-xl p-8 flex flex-col items-center justify-center bg-slate-800/50 hover:bg-slate-700/50 transition-colors cursor-pointer"
          onClick={() => fileInputRef.current?.click()}
        >
          <input 
            type="file" 
            ref={fileInputRef} 
            onChange={handleFileChange} 
            accept=".json" 
            className="hidden" 
          />
          
          {!file ? (
            <>
              <UploadCloud className="h-12 w-12 text-slate-400 mb-4" />
              <p className="text-slate-300 font-medium mb-1">Click to browse or drag and drop</p>
              <p className="text-slate-500 text-sm">JSON report files only</p>
              <button className="mt-6 px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-lg text-sm font-medium transition-colors">
                Choose JSON Report
              </button>
            </>
          ) : (
            <>
              <FileJson className="h-12 w-12 text-blue-500 mb-4" />
              <p className="text-white font-medium mb-1 truncate max-w-xs">{file.name}</p>
              <p className="text-slate-400 text-sm">{(file.size / 1024).toFixed(2)} KB • JSON File</p>
              <button 
                className="mt-4 px-4 py-1.5 border border-slate-600 hover:border-slate-500 text-slate-300 rounded-lg text-xs transition-colors"
                onClick={(e) => { e.stopPropagation(); setFile(null); setError(null); }}
              >
                Change File
              </button>
            </>
          )}
        </div>

        {error && (
          <div className="mt-4 p-4 bg-red-900/30 border border-red-500/30 rounded-lg flex items-start space-x-3">
            <AlertCircle className="h-5 w-5 text-red-500 mt-0.5 flex-shrink-0" />
            <p className="text-red-200 text-sm">{error}</p>
          </div>
        )}

        <div className="mt-6 flex justify-end">
          <button 
            onClick={handleUpload}
            disabled={!file || loading}
            className={`px-6 py-2.5 rounded-lg font-medium flex items-center justify-center min-w-[140px] transition-all
              ${!file || loading 
                ? 'bg-blue-600/50 text-white/50 cursor-not-allowed' 
                : 'bg-blue-600 hover:bg-blue-500 text-white shadow-lg shadow-blue-500/20'}`}
          >
            {loading ? (
              <><Loader2 className="animate-spin h-5 w-5 mr-2" /> Analyzing...</>
            ) : (
              'Analyze Report'
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
